### ISSUE TITLE
Error when launching open player on godot engine

### ISSUE THREAD

**Issue by ShawkMusic** [nathanfranke/open-player#2]
I get this error:
`Invalid get index 'theme' (on base: 'Nil').`

![image](https://user-images.githubusercontent.com/48574225/150176150-07cd6a2f-0ace-4eed-91ff-891e5d01c455.png)

**Comment by ShawkMusic** [comment]
I also got this error when first opening it in the editor
![image](https://user-images.githubusercontent.com/48574225/150176756-9b03973d-4bf5-4e9d-9f0b-b6d5a5f3719b.png)

**Comment by nathanfranke** [comment]
> I also got this error when first opening it in the editor

I think I've gotten that before- Click OK, then go to Project Settings -> Addons and re-enable it. I will research if there's a better way to fix it.

**Comment by ShawkMusic** [comment]
I did that, still doesn't work.

I tried restarting the editor, and still the same thing

Also here's the full Debugger errors if that helps at all
![image](https://user-images.githubusercontent.com/48574225/150177591-8271d14e-9531-42cf-bb63-f7da1664022b.png)

**Comment by nathanfranke** [comment]
`res://App/Model/Track.gd` isn't a valid path, since I renamed all the directories to be lowercase. I think your configuration is from an older version. In `~/.local/share/godot/app_userdata`, can you rename `OpenPlayer` to `OpenPlayer.old`?

**Comment by ShawkMusic** [comment]
It's working now :) thanks

**Comment by nathanfranke** [comment]
> I also got this error when first opening it in the editor ![image](https://user-images.githubusercontent.com/48574225/150176756-9b03973d-4bf5-4e9d-9f0b-b6d5a5f3719b.png)

Properly fixed in b72b4b0358c0441665fb0f865cd5c3cda64dfc2a
